services:
  z-way-server:
    build:
      context: .
    container_name: z-way-container
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 # For Z-Wave USB Stick
#      - /dev/ttyUSB1:/dev/ttyUSB1 # For additional interface like a ZigBee stick
    ports:
      - "8083:8083"
    volumes:
      - ./data:/data
    restart: unless-stopped
